import type { NextPage } from "next";
import Head from "next/head";
import { Button } from "antd";
import { Switch } from "antd";

const Home: NextPage = () => {
  const onChange = (checked: boolean) => {
    console.log(`switch to ${checked}`);
  };

  return (
    <div>
      <Head>
        <title>Proyecto Base de datos 1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-red-600 text-3xl">Hello world</div>
      <Button type="primary">Hello world</Button>

      <Switch defaultChecked onChange={onChange} />
    </div>
  );
};

export default Home;
