import { pageTitle } from "$config/site";
import type { NextPage } from "next";
import Head from "next/head";
import Header from "$templates/Header";

const Login: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Login - {pageTitle}</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="/favicon.png" />
      </Head>
      <Header />
      Login
    </div>
  );
};

export default Login;
