import { pageTitle } from "$config/site";
import type { NextPage } from "next";
import Head from "next/head";
import Header from "$templates/Header";
import { Input, Button } from "antd";
import { LockOutlined, MailOutlined } from "@ant-design/icons";
import { Typography } from "antd";

const { Title, Text } = Typography;
const Login: NextPage = () => {
  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>Iniciar sesión - {pageTitle}</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="/favicon.png" />
      </Head>
      <Header />
      <div className="flex flex-col flex-1 justify-center items-center">
        <div className="flex flex-col w-96 gap-6">
          <div className="flex flex-col w-full items-center mb-8">
            <Title level={3} className="!text-blue-500 text-center">
              Iniciar sesión
            </Title>
            <Text className="text-center">Inicia sesión para continuar</Text>
          </div>

          <Input
            type={"email"}
            size="large"
            placeholder="Ingresa tu correo electrónico"
            prefix={<MailOutlined />}
          />
          <Input.Password
            type={"password"}
            size="large"
            placeholder="Ingresa tu contraseña"
            prefix={<LockOutlined />}
          />
          <Button
            size="large"
            type="primary"
            loading={false}
            onClick={() => console.log("set loading true")}
          >
            Iniciar sesión
          </Button>
        </div>
      </div>
    </div>
  );
};

export default Login;
