import { NextPage } from "next";
import Header from "$templates/Header";
import { Breadcrumb, Button, Modal } from "antd";
import Link from "next/link";
import { useLogin } from "$hooks/useLogin";
import AccessDenied from "$templates/AccessDenied";
import Head from "next/head";
import { pageTitle } from "$config/site";
import ProductsTable from "$templates/ProductsTable";
import { useState } from "react";
import CreateProduct from "$templates/CreateProduct";

const Products: NextPage = () => {
  const [isLoggedIn, mounted] = useLogin();
  const [showCreateProductModal, setShowCreateProductModal] =
    useState<boolean>(false);

  return (
    <>
      <Head>
        <title>Productos - {pageTitle}</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/png" href="/favicon.png" />
      </Head>
      <Header />
      <div className="w-full flex flex-col items-center">
        {mounted && (
          <div className="container mb-8">
            {isLoggedIn ? (
              <>
                <div className="h-16 flex items-center w-full">
                  <Breadcrumb>
                    <Breadcrumb.Item>
                      <Link href="/">
                        <a>Inicio</a>
                      </Link>
                    </Breadcrumb.Item>
                    <Breadcrumb.Item>
                      <Link href="/products">
                        <a>Productos</a>
                      </Link>
                    </Breadcrumb.Item>
                  </Breadcrumb>
                </div>
                <div className="flex mt-5 justify-end">
                  <Button
                    type="primary"
                    onClick={() => setShowCreateProductModal(true)}
                  >
                    Crear producto
                  </Button>
                </div>
                <div className="mt-5 overflow-x-auto">
                  <ProductsTable />
                </div>
              </>
            ) : (
              <div className="flex justify-center items-center w-full min-h-[calc(100vh-4rem)]">
                <AccessDenied />
              </div>
            )}
          </div>
        )}
        <Modal
          title="Crear producto"
          closable={false}
          visible={showCreateProductModal}
          footer={null}
          destroyOnClose
        >
          <CreateProduct
            product={null}
            modalType="create"
            setShowModal={setShowCreateProductModal}
          />
        </Modal>
      </div>
    </>
  );
};

export default Products;
